github = "Juuxel/PaintersBlocks"
loaders = ["fabric", "quilt"]
game_versions = ["1.20.1"]

[modrinth]
project_id = "c5SJLLsl"
slug = "painters-blocks"

[[modrinth.dependencies]] # fabric api
project_id = "P7dR8mSH"

[curseforge]
project_id = "499776"
slug = "painters-blocks"

[[curseforge.relations]]
slug = "fabric-api"
